/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_ANOMALY_METADATA_H_
#define _EI_CLASSIFIER_ANOMALY_METADATA_H_

#include "edge-impulse-sdk/classifier/ei_model_types.h"

const uint16_t ei_classifier_anom_axes_1005259_4[] = { 0, 13, 26 };

// (before - mean) / scale
const float ei_classifier_anom_scale_1005259_4[3] = { 949.9793063368621, 842.5628013095258, 1405.0826166854563 };
const float ei_classifier_anom_mean_1005259_4[3] = { 1273.930149450848, 856.8244101142241, 1274.0683297051323 };
const ei_classifier_anom_cluster_t ei_classifier_anom_clusters_1005259_4[32] = {
	{ ( float[3] ) { 0.64951092004776, -0.2969980239868164, -0.35650211572647095 }, 0.16290928721367412 },
	{ ( float[3] ) { 0.65118408203125, -0.30630794167518616, -0.5125945806503296 }, 0.1209177673524819 },
	{ ( float[3] ) { -1.2843830585479736, -0.9556372165679932, -0.8381908535957336 }, 0.033155879678546336 },
	{ ( float[3] ) { -0.004988717380911112, 0.9449133276939392, 0.9232657551765442 }, 0.22174538070914002 },
	{ ( float[3] ) { 1.1971311569213867, 1.1647051572799683, 1.2536273002624512 }, 0.12552233918086722 },
	{ ( float[3] ) { 0.3914007544517517, 1.6769260168075562, 1.6779248714447021 }, 0.04037139412115731 },
	{ ( float[3] ) { 0.5901170372962952, 1.3492292165756226, 1.3272368907928467 }, 0.17688661123075528 },
	{ ( float[3] ) { 0.40441659092903137, -0.43071117997169495, -0.5824844241142273 }, 0.1392299607965469 },
	{ ( float[3] ) { 0.8916553854942322, 1.6546674966812134, 1.572155237197876 }, 0.2167109034222717 },
	{ ( float[3] ) { 0.5803737640380859, 0.8463534712791443, 1.57969069480896 }, 0.07040901452462153 },
	{ ( float[3] ) { 0.1220206469297409, -0.5186912417411804, -0.6230309009552002 }, 0.12469519646960885 },
	{ ( float[3] ) { 0.8025414347648621, -0.30281656980514526, -0.5185783505439758 }, 0.1389162480464899 },
	{ ( float[3] ) { 0.5522491335868835, -0.4433576762676239, -0.544935941696167 }, 0.12854093846825124 },
	{ ( float[3] ) { 0.6965019702911377, 1.872838020324707, 1.512524962425232 }, 0.217759095491218 },
	{ ( float[3] ) { 0.5047496557235718, 1.9144052267074585, 1.788837194442749 }, 0 },
	{ ( float[3] ) { -0.01945054717361927, 0.9235715866088867, 1.1768081188201904 }, 0.13646516791904528 },
	{ ( float[3] ) { 0.8998232483863831, -0.24752530455589294, -0.4028925597667694 }, 0.149468917898057 },
	{ ( float[3] ) { 1.4081305265426636, 2.11751651763916, 1.972983956336975 }, 0.12085343419949057 },
	{ ( float[3] ) { 0.08305401355028152, 1.1193161010742188, 1.3377515077590942 }, 0.22954839362197604 },
	{ ( float[3] ) { 1.6460421085357666, 2.0181503295898438, 1.9845880270004272 }, 0.19399147470772926 },
	{ ( float[3] ) { 0.5164543986320496, 0.7931277751922607, 1.1949865818023682 }, 0.24736988143587105 },
	{ ( float[3] ) { 0.2482675313949585, 1.1412039995193481, 1.1720430850982666 }, 0.10765210906353816 },
	{ ( float[3] ) { 0.8127901554107666, 0.08390025794506073, -0.5283257365226746 }, 0.09566771344210519 },
	{ ( float[3] ) { 1.9835084676742554, 1.0127792358398438, 1.8326531648635864 }, 0 },
	{ ( float[3] ) { 1.303749918937683, 1.3831583261489868, 1.3971259593963623 }, 0.10602475119161117 },
	{ ( float[3] ) { 0.5786259770393372, 1.63412344455719, 1.2761200666427612 }, 0.11475118896838131 },
	{ ( float[3] ) { 0.7861535549163818, 2.085305690765381, 1.7363810539245605 }, 0.20118668616178087 },
	{ ( float[3] ) { 1.860072374343872, 1.0691394805908203, 1.5163142681121826 }, 0.15176695221768668 },
	{ ( float[3] ) { 2.0393245220184326, 1.3311949968338013, 1.5687243938446045 }, 0.08039152757973847 },
	{ ( float[3] ) { 1.5491530895233154, 1.5944048166275024, 1.710142731666565 }, 0 },
	{ ( float[3] ) { 0.37466511130332947, 1.6773215532302856, 1.448298692703247 }, 0 },
	{ ( float[3] ) { 1.1154295206069946, 1.916603922843933, 1.7850844860076904 }, 0 },
};

#endif // _EI_CLASSIFIER_ANOMALY_METADATA_H_
